# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embed.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'embed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mbed.proto\x12\x08\x64t.embed\x1a\x0c\x63ommon.proto\",\n\x0c\x45mbedRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\r\n\x05model\x18\x02 \x01(\t\"\x1b\n\tEmbedding\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"L\n\rEmbedResponse\x12\'\n\nembeddings\x18\x01 \x03(\x0b\x32\x13.dt.embed.Embedding\x12\x12\n\nmodel_used\x18\x02 \x01(\t2v\n\x0c\x45mbedService\x12\x38\n\x05\x45mbed\x12\x16.dt.embed.EmbedRequest\x1a\x17.dt.embed.EmbedResponse\x12,\n\x06Health\x12\x10.dt.common.Empty\x1a\x10.dt.common.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDREQUEST']._serialized_start=39
  _globals['_EMBEDREQUEST']._serialized_end=83
  _globals['_EMBEDDING']._serialized_start=85
  _globals['_EMBEDDING']._serialized_end=112
  _globals['_EMBEDRESPONSE']._serialized_start=114
  _globals['_EMBEDRESPONSE']._serialized_end=190
  _globals['_EMBEDSERVICE']._serialized_start=192
  _globals['_EMBEDSERVICE']._serialized_end=310
# @@protoc_insertion_point(module_scope)
