#!/bin/bash
# ============================================================
# Personal Digital Twin — 一键部署脚本
# 用法: bash setup.sh
# ============================================================
set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }

INSTALL_DIR="${INSTALL_DIR:-/data/myProject}"
CONFIG="${CONFIG:-$INSTALL_DIR/config.yaml}"

echo "============================================"
echo " Personal Digital Twin — Setup"
echo "============================================"
echo ""

# ---- 1. 基础依赖 ----
log "检查基础依赖..."
command -v python3  >/dev/null || err "需要 Python 3.10+"
command -v curl     >/dev/null || err "需要 curl"
command -v cargo    >/dev/null || warn "cargo 未安装 (跳过 code-indexer 编译)"
command -v systemctl >/dev/null || warn "非 systemd 系统 (需手动管理服务)"

# ---- 2. 外部服务检查 ----
log "检查外部服务..."
for svc in neo4j qdrant; do
  systemctl is-active --quiet $svc 2>/dev/null && log "  $svc 已运行" || warn "  $svc 未运行，请先安装启动"
done

# ---- 3. Embed Server ----
log "部署 Embed Server..."
if [ ! -d "$INSTALL_DIR/embed-server" ]; then
  mkdir -p "$INSTALL_DIR/embed-server"
  cat > "$INSTALL_DIR/embed-server/main.py" << 'PYEOF'
# Embedding server for BGE-base-zh-v1.5
# Auto-generated by setup.sh
import os, json
from flask import Flask, request, jsonify
from sentence_transformers import SentenceTransformer

MODEL = os.environ.get("EMBED_MODEL", "BAAI/bge-base-zh-v1.5")
model = SentenceTransformer(MODEL)
app = Flask(__name__)

@app.route("/health")
def health():
    return jsonify({"status": "ok", "model": MODEL, "dim": 768})

@app.route("/embed", methods=["POST"])
def embed():
    text = request.json.get("text", "")
    vec = model.encode([text], normalize_embeddings=True)[0].tolist()
    return jsonify({"vector": vec})

@app.route("/embed-batch", methods=["POST"])
def embed_batch():
    texts = request.json.get("texts", [])
    vecs = model.encode(texts, normalize_embeddings=True, show_progress_bar=False).tolist()
    return jsonify({"vectors": vecs, "dim": 768})

if __name__ == "__main__":
    import waitress
    waitress.serve(app, host="0.0.0.0", port=8001)
PYEOF
  cat > "$INSTALL_DIR/embed-server/requirements.txt" << 'EOF'
sentence-transformers>=2.2.0
flask>=2.0
waitress>=2.0
EOF
  pip install -r "$INSTALL_DIR/embed-server/requirements.txt" -q
fi

# ---- 4. Systemd 服务 ----
log "注册 systemd 服务..."
for svc in embed-server code-search digital-twin-watch; do
  if [ -f "/etc/systemd/system/${svc}.service" ]; then
    log "  ${svc}.service 已存在"
  else
    warn "  ${svc}.service 未找到，请手动创建"
  fi
done

# ---- 5. 索引代码 (可选) ----
if [ -n "$INDEX_PROJECTS" ]; then
  log "索引项目代码..."
  if command -v code-indexer >/dev/null; then
    for proj in ${INDEX_PROJECTS//,/ }; do
      name=${proj##*/}
      code-indexer index --path "$proj" --name "$name" || warn "  索引 $name 失败"
    done
  fi
fi

# ---- 6. 初始化知识图谱 ----
log "初始化 Neo4j Schema..."
python3 -c "
import json, urllib.request
URL='http://localhost:7474/db/neo4j/tx/commit'
AUTH='bmVvNGo6bmVvNGo='
for stmt in [
    'CREATE CONSTRAINT IF NOT EXISTS FOR (n:Method) REQUIRE n.method_id IS UNIQUE',
    'CREATE CONSTRAINT IF NOT EXISTS FOR (n:Class) REQUIRE n.class_id IS UNIQUE',
    'CREATE CONSTRAINT IF NOT EXISTS FOR (n:Interface) REQUIRE n.interface_id IS UNIQUE',
    'CREATE CONSTRAINT IF NOT EXISTS FOR (n:Enum) REQUIRE n.enum_id IS UNIQUE',
    'CREATE CONSTRAINT IF NOT EXISTS FOR (n:Project) REQUIRE n.project_id IS UNIQUE',
    'CREATE CONSTRAINT IF NOT EXISTS FOR (n:Document) REQUIRE n.doc_id IS UNIQUE',
    'CREATE CONSTRAINT IF NOT EXISTS FOR (n:Event) REQUIRE n.event_id IS UNIQUE',
    'CREATE CONSTRAINT IF NOT EXISTS FOR (n:Package) REQUIRE n.package_id IS UNIQUE',
    'CREATE CONSTRAINT IF NOT EXISTS FOR (n:Module) REQUIRE n.module_id IS UNIQUE',
    'CREATE INDEX IF NOT EXISTS FOR (n:Method) ON (n.project)',
    'CREATE INDEX IF NOT EXISTS FOR (n:Method) ON (n.name)',
    'CREATE INDEX IF NOT EXISTS FOR (n:Event) ON (n.type)',
    'CREATE INDEX IF NOT EXISTS FOR (n:Event) ON (n.timestamp)',
]:
    data=json.dumps({'statements':[{'statement':stmt}]}).encode()
    req=urllib.request.Request(URL,data=data,headers={'Content-Type':'application/json','Authorization':f'Basic {AUTH}'})
    urllib.request.urlopen(req,timeout=30)
print('Schema ready')
"

# ---- 7. 扫描环境 ----
log "扫描当前环境..."
python3 "$INSTALL_DIR/scripts/env-scan.py" 2>/dev/null || warn "  环境扫描脚本未找到，跳过"

echo ""
echo "============================================"
echo " 部署完成!"
echo "============================================"
echo ""
echo "  启动服务:"
echo "    sudo systemctl start embed-server code-search digital-twin-watch"
echo ""
echo "  验证:"
echo "    curl http://localhost:3001          # Web UI"
echo "    curl http://localhost:8001/health   # Embed Server"
echo ""
echo "  索引项目:"
echo "    code-indexer index --path /path/to/project --name my-project"
echo ""
echo "  配置 LLM (可选):"
echo "    export LLM_API_KEY=sk-xxx"
echo "    python3 generate_summaries.py"
